kind: ServiceAccount
apiVersion: v1
metadata:
  namespace: chaos-testing
  name: account-chaos-testing-manager-fywav

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: chaos-testing
  name: role-chaos-testing-manager-fywav
rules:
- apiGroups: [""]
  resources: ["pods", "namespaces"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["chaos-mesh.org"]
  resources: [ "*" ]
  verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bind-chaos-testing-manager-fywav
  namespace: chaos-testing
subjects:
- kind: ServiceAccount
  name: account-chaos-testing-manager-fywav
  namespace: chaos-testing
roleRef:
  kind: Role
  name: role-chaos-testing-manager-fywav
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: clusterrole-chaos-testing-manager-fywav
rules:
- apiGroups: [""]
  resources: ["pods", "namespaces"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["chaos-mesh.org"]
  resources: [ "workflows", "*" ]
  verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bind-chaos-testing-manager-fywav
subjects:
- kind: ServiceAccount
  name: account-chaos-testing-manager-fywav
  namespace: chaos-testing
roleRef:
  kind: ClusterRole
  name: clusterrole-chaos-testing-manager-fywav
  apiGroup: rbac.authorization.k8s.io
